// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkpENF84-6LJ-Yr2LnLla-udUSqXn5D90',
    appId: '1:272759135129:web:2db52fbec3dbc36c551108',
    messagingSenderId: '272759135129',
    projectId: 'flutter-data-firebase-b5c6f',
    authDomain: 'flutter-data-firebase-b5c6f.firebaseapp.com',
    storageBucket: 'flutter-data-firebase-b5c6f.appspot.com',
    measurementId: 'G-X8F3VS46KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC67ZZkmo7KFLKcbiwtCgK3Cl4aYKRLkV8',
    appId: '1:272759135129:android:27b5b72626645c4a551108',
    messagingSenderId: '272759135129',
    projectId: 'flutter-data-firebase-b5c6f',
    storageBucket: 'flutter-data-firebase-b5c6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoTpDoEBypxZfYAO_9xAfMOh7wgl5ePKM',
    appId: '1:272759135129:ios:fb62a54e2d93cd88551108',
    messagingSenderId: '272759135129',
    projectId: 'flutter-data-firebase-b5c6f',
    storageBucket: 'flutter-data-firebase-b5c6f.appspot.com',
    iosClientId: '272759135129-q2953pnfbb8fhnke7sroibibc16k64bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoTpDoEBypxZfYAO_9xAfMOh7wgl5ePKM',
    appId: '1:272759135129:ios:fb62a54e2d93cd88551108',
    messagingSenderId: '272759135129',
    projectId: 'flutter-data-firebase-b5c6f',
    storageBucket: 'flutter-data-firebase-b5c6f.appspot.com',
    iosClientId: '272759135129-q2953pnfbb8fhnke7sroibibc16k64bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoList',
  );
}
